autoscaler:
  image:
  # docker pull ghcr.io/middleware-labs/odigos-odiglet:middleware-test-0.0.1
    repository: ghcr.io/middleware-labs/odigos-autoscaler:middleware-test-0.0.1
    tag: v0.1.44

scheduler:
  image:
    repository: ghcr.io/middleware-labs/odigos-scheduler:middleware-test-0.0.1
    tag: v0.1.44

langDetector:
  image:
    repository: ghcr.io/middleware-labs/odigos-lang-detector:middleware-test-0.0.1
    tag: v0.1.44

ui:
  image:
    repository: ghcr.io/middleware-labs/odigos-ui:middleware-test-0.0.1
    tag: v0.1.44

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: ghcr.io/middleware-labs/odigos-instrumentor:middleware-test-0.0.1
    tag: v0.1.44

odiglet:
  image:
    repository: ghcr.io/middleware-labs/odigos-odiglet:middleware-test-0.0.1
    tag: v0.1.44

telemetry:
  enabled: true
