autoscaler:
  image:
    repository: ghcr.io/middleware-labs/odigos-autoscaler
    tag: v0.1.44

scheduler:
  image:
    repository: ghcr.io/middleware-labs/odigos-scheduler
    tag: v0.1.44

langDetector:
  image:
    repository: ghcr.io/middleware-labs/odigos-lang-detector
    tag: v0.1.44

ui:
  image:
    repository: ghcr.io/middleware-labs/odigos-ui
    tag: v0.1.44

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: ghcr.io/middleware-labs/odigos-instrumentor
    tag: v0.1.44

odiglet:
  image:
    repository: ghcr.io/middleware-labs/odigos-odiglet
    tag: v0.1.44

telemetry:
  enabled: true
